name: Vercel Production Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch: # Permite ejecución manual

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun i
      - name: Run Tests
        run: bun test

  Deploy:
    needs: test
    environment: Production
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
      - name: Install Vercel CLI
        run: bun i vercel@latest
      - name: Build Project API routes
        run: bun run build # Vercel has a problem when building standalone servers if there are no files to delete.
      - name: Pull Vercel Environment Information
        run: bun vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: bun vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: bun vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}